### ISSUE TITLE
Not all download links work

### ISSUE THREAD

**Issue by EvelinaBiserova** [ugeneunipro/ugeneunipro.github.io#40]
Site | Link text | Link | Result
---- | --------- | ---- | -------
[download](https://ugeneunipro.github.io/download.html), [download (ru)](https://ugeneunipro.github.io/ru/download.html) | ` UGENE for Windows`, `Download UGENE for Windows` | http://archive.ugene.net/downloads/installer_windows_x64.exe | "404 Not Found": Not Found. The requested URL was not found on this server.
[download-all](https://ugeneunipro.github.io/download-all.html) | `UGENE Online Installer for Windows 64-bit` | https://f000.backblazeb2.com/file/uniprougene/release-archive/installer_windows_x32.exe | { "code": "not_found", "message": "File with such name does not exist.", "status": 404 }
[download-all](https://ugeneunipro.github.io/download-all.html) | `UGENE Online Installer for` Linux 64-bit, macOS | https://ugeneunipro.github.io/download-all.html | Wrong link
[download-all](https://ugeneunipro.github.io/download-all.html) | Reference Data for NGS | Links like https://f000.backblazeb2.com/file/uniprougene/release-archive/some_archive.7z | { "code": "not_found", "message": "File with such name does not exist.", "status": 404 }
[download-all](https://ugeneunipro.github.io/download-all.html) | `Windows 7+ (64-bit) Zip archive NGS Package`, `Linux (64-bit) TAR.GZ archive Full Package`, `Linux (64-bit) TAR.GZ archive NGS Package`, `macOS 10.7+ (64-bit) DMG installer NGS Package` | Links like https://f000.backblazeb2.com/file/uniprougene/release-archive/ugene-33.0-win-x86-64-portable-NGS.zip | { "code": "not_found", "message": "File with such name does not exist.", "status": 404 }
[download-all](https://ugeneunipro.github.io/download-all.html) | `External Tools Package for` Linux 64-bit, Linux 32-bit, macOS | Links like https://f000.backblazeb2.com/file/uniprougene/release-archive/ext_tools_linux_64-bit.tar.gz | { "code": "not_found", "message": "File with such name does not exist.", "status": 404 }
[download-all (ru)](https://ugeneunipro.github.io/ru/download-all.html) | Референсные данные для NGS | Links like http://archive.ugene.net/downloads/downloadable_data/taxonomy.7z | "404 Not Found": Not Found. The requested URL was not found on this server.

**Comment by yalgaer** [comment]
Fixed.

**Comment by EvelinaBiserova** [comment]
[download-all](http://ugene.net/download-all.html)

- Linux (64-bit) TAR.GZ archive Full Package,
- Linux (64-bit) TAR.GZ archive NGS Package,
- macOS 10.7+ (64-bit) DMG installer NGS Package

still don't work
